name: PHPCS

on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpcs, cs2pr
      - name: Run PHPCS
        run: phpcs --report=checkstyle | cs2pr
